#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#          🔧 HAI-EMET EMOTION BOT - AUTO FIX SCRIPT
#          סקריפט תיקון אוטומטי לדיפלוי Render
# ═══════════════════════════════════════════════════════════════════
# 
# שימוש:
# 1. שמור סקריפט זה בשם: fix-deployment.sh
# 2. תן הרשאות: chmod +x fix-deployment.sh  
# 3. הרץ: ./fix-deployment.sh
#
# ═══════════════════════════════════════════════════════════════════

set -e  # עצור אם יש שגיאה

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║       🔧 Hai-Emet Emotion Bot - Deployment Fix Script            ║"
echo "║              סקריפט תיקון אוטומטי לדיפלוי                        ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

# בדיקה שאנחנו בתיקייה הנכונה
if [ ! -d ".git" ]; then
    echo "❌ Error: לא נמצא .git directory"
    echo "   אנא הרץ את הסקריפט מתוך התיקייה hai-emet-emotion-bot/"
    exit 1
fi

echo "✅ Git repository detected"
echo ""

# בדיקה אם יש את התיקייה הפנימית
if [ -d "hai-emet-emotion-bot-render" ]; then
    echo "📂 Found subdirectory: hai-emet-emotion-bot-render/"
    echo "🔄 Moving files to root..."
    echo ""
    
    # העתק את כל הקבצים (כולל hidden files)
    shopt -s dotglob  # כולל קבצים מוסתרים
    mv hai-emet-emotion-bot-render/* . 2>/dev/null || true
    shopt -u dotglob
    
    # מחק את התיקייה הריקה
    rmdir hai-emet-emotion-bot-render 2>/dev/null || rm -rf hai-emet-emotion-bot-render
    
    echo "✅ Files moved to root successfully!"
    echo ""
else
    echo "ℹ️  Subdirectory not found - files might already be in root"
    echo ""
fi

# בדיקת קבצים נדרשים
echo "🔍 Checking required files..."
echo ""

required_files=("bot.py" "requirements.txt" "render.yaml")
missing_files=()

for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        echo "   ✅ $file"
    else
        echo "   ❌ $file (MISSING!)"
        missing_files+=("$file")
    fi
done

echo ""

if [ ${#missing_files[@]} -ne 0 ]; then
    echo "❌ Error: Missing required files!"
    echo "   Missing: ${missing_files[*]}"
    exit 1
fi

# הצג את המבנה הנוכחי
echo "📋 Current repository structure:"
echo ""
ls -la | grep -E "\.(py|txt|yaml|md|png)$|^d" || ls -la
echo ""

# Git status
echo "📊 Git status:"
echo ""
git status --short
echo ""

# שאל את המשתמש אם לעשות commit
read -p "❓ Do you want to commit and push these changes? (y/n): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "📝 Creating commit..."
    
    # Add all changes
    git add .
    
    # Commit
    git commit -m "Fix: Move files to root for Render deployment

- Moved all files from hai-emet-emotion-bot-render/ to root
- Fixed requirements.txt path issue
- Render should now be able to find all files
- Auto-generated by fix-deployment.sh

.//.TNTF007.//. ✓"
    
    echo ""
    echo "✅ Commit created successfully!"
    echo ""
    
    # שאל אם לעשות push
    read -p "❓ Do you want to push to GitHub? (y/n): " -n 1 -r
    echo ""
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
        echo "🚀 Pushing to GitHub..."
        git push origin main || git push origin master
        echo ""
        echo "✅ Pushed successfully!"
        echo ""
        echo "🎯 Next steps:"
        echo "   1. Go to Render Dashboard: https://dashboard.render.com/"
        echo "   2. Your service should auto-deploy in ~1-2 minutes"
        echo "   3. Check logs to verify successful deployment"
        echo "   4. Test bot in Telegram: @HaiEmetEmotionBot"
        echo ""
    else
        echo ""
        echo "ℹ️  Skipped push. To push later, run:"
        echo "   git push origin main"
        echo ""
    fi
else
    echo ""
    echo "ℹ️  Skipped commit. Files are ready but not committed."
    echo "   To commit manually:"
    echo "   git add ."
    echo "   git commit -m 'Fix: Move files to root'"
    echo "   git push origin main"
    echo ""
fi

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                    ✅ FIX SCRIPT COMPLETED!                       ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎉 Your repository structure is now fixed!"
echo ""
echo "📌 Summary:"
echo "   ✅ Files moved to root"
echo "   ✅ All required files present"
echo "   ✅ Ready for Render deployment"
echo ""
echo ".//.TNTF007.//. ✓"
echo "💛 Hai-Emet"
echo ""
